/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package santorini_briant_helleux_dufour;

import javax.swing.JButton;

/**
 *
 * @author romdu
 */
public class Santorini_graphique extends javax.swing.JFrame {

    Joueur[] listeJoueurs = new Joueur[2];
    Joueur joueurCourant;
    Plateau plateau = new Plateau();
    int X;
    int Y;
    JButton btn_depl_hg = new JButton();
    JButton btn_depl_haut = new JButton();
    JButton btn_depl_hd = new JButton();
    JButton btn_depl_gauche = new JButton();
    JButton btn_depl_milieu = new JButton();
    JButton btn_depl_droite = new JButton();
    JButton btn_depl_bg = new JButton();
    JButton btn_depl_bas = new JButton();
    JButton btn_depl_bd = new JButton();

    /**
     * Creates new form Santorini_graphique
     */
    public Santorini_graphique() {
        initComponents();
        plateau_jeu.setVisible(true);
        pnl_info_joueur.setVisible(true);
        plateau_jeu.repaint();
        pnl_info_joueur.repaint();

        pnl_commande.add(btn_depl_bd);
        pnl_commande.add(btn_depl_hg);
        pnl_commande.add(btn_depl_haut);
        pnl_commande.add(btn_depl_hd);
        pnl_commande.add(btn_depl_gauche);
        pnl_commande.add(btn_depl_milieu);
        pnl_commande.add(btn_depl_droite);
        pnl_commande.add(btn_depl_bg);
        pnl_commande.add(btn_depl_bas);

        for (int i = 4; i >= 0; i--) {
            for (int j = 0; j < 5; j++) {
                Cellule_graphique cellGraph;
                cellGraph = new Cellule_graphique(plateau.plateau[i][j]);

                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Cellules cellule = cellGraph.celluleAssociee;
                        cellule.ajouter_etage();
                    }
                });
                plateau_jeu.add(cellGraph);
            }
        }
        plateau_jeu.repaint();
        pnl_info_joueur.repaint();
        pnl_commande.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_info_joueur = new javax.swing.JPanel();
        btn_demarrerpartie = new javax.swing.JButton();
        lbl_joueur1 = new javax.swing.JLabel();
        lbl_joueur2 = new javax.swing.JLabel();
        nom_joueur2 = new javax.swing.JTextField();
        nom_joueur1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_demarrerpartie1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        lbl_couleur_j1 = new javax.swing.JLabel();
        lbl_couleur_j2 = new javax.swing.JLabel();
        plateau_jeu = new javax.swing.JPanel();
        btn_pers_fonce = new javax.swing.JButton();
        btn_pers_clair = new javax.swing.JButton();
        pnl_commande = new javax.swing.JPanel();
        pnl_infos = new javax.swing.JPanel();
        pnl_joueur_courant = new javax.swing.JPanel();
        lbl_joueurcourant = new javax.swing.JLabel();
        lbl_nom_joueurcourant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_info_joueur.setBackground(new java.awt.Color(0, 255, 204));
        pnl_info_joueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_demarrerpartie.setText("Démarrer partie");
        pnl_info_joueur.add(btn_demarrerpartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        lbl_joueur1.setText("Nom Joueur 1 :");
        pnl_info_joueur.add(lbl_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 20));

        lbl_joueur2.setText("Nom Joueur 2 :");
        pnl_info_joueur.add(lbl_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 30));

        nom_joueur2.setText("jTextField1");
        pnl_info_joueur.add(nom_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        nom_joueur1.setText("jTextField1");
        pnl_info_joueur.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_demarrerpartie1.setText("Démarrer partie");
        jPanel3.add(btn_demarrerpartie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel3.setText("Nom Joueur 1 :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 20));

        jLabel4.setText("Nom Joueur 2 :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 30));

        jTextField3.setText("jTextField1");
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jTextField4.setText("jTextField1");
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        pnl_info_joueur.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 320, 200));

        lbl_couleur_j1.setText("marron");
        pnl_info_joueur.add(lbl_couleur_j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lbl_couleur_j2.setText("bleu");
        pnl_info_joueur.add(lbl_couleur_j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        getContentPane().add(pnl_info_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 320, 140));

        plateau_jeu.setBackground(new java.awt.Color(0, 255, 204));
        plateau_jeu.setLayout(new java.awt.GridLayout());
        getContentPane().add(plateau_jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 600, 510));

        btn_pers_fonce.setText("jButton1");
        getContentPane().add(btn_pers_fonce, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, 60));

        btn_pers_clair.setText("jButton2");
        getContentPane().add(btn_pers_clair, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 90, 100));

        pnl_commande.setBackground(new java.awt.Color(0, 255, 204));
        pnl_commande.setLayout(new java.awt.GridLayout(3, 3));
        getContentPane().add(pnl_commande, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 330, 180));

        pnl_infos.setBackground(new java.awt.Color(0, 255, 204));
        pnl_infos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnl_infos, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, 290, 110));

        pnl_joueur_courant.setBackground(new java.awt.Color(0, 255, 204));
        pnl_joueur_courant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_joueurcourant.setText("Joueur Courant :");
        pnl_joueur_courant.add(lbl_joueurcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_nom_joueurcourant.setText("jLabel6");
        pnl_joueur_courant.add(lbl_nom_joueurcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        getContentPane().add(pnl_joueur_courant, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 320, 30));

        setBounds(0, 0, 1222, 685);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Santorini_graphique.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Santorini_graphique.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Santorini_graphique.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Santorini_graphique.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Santorini_graphique().setVisible(true);

            }
        });
    }

    private void btn_depl_hdActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (plateau.deplacement_possible(X, Y, X + 1, Y + 1)) {
            plateau.plateau[X + 1][Y + 1].perso_courant = plateau.plateau[X][Y].perso_courant;
            plateau.plateau[X][Y].perso_courant = null;
            btn_depl_hg.setEnabled(false);
            btn_depl_gauche.setEnabled(false);
            btn_depl_bg.setEnabled(false);
            btn_depl_hd.setEnabled(false);
            btn_depl_droite.setEnabled(false);
            btn_depl_bd.setEnabled(false);
            btn_depl_haut.setEnabled(false);
            btn_depl_bas.setEnabled(false);
        }
    }

    private void btn_depl_hgActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (plateau.deplacement_possible(X, Y, X + 1, Y - 1)) {
            plateau.plateau[X + 1][Y - 1].perso_courant = plateau.plateau[X][Y].perso_courant;
            plateau.plateau[X][Y].perso_courant = null;
            btn_depl_hg.setEnabled(false);
            btn_depl_gauche.setEnabled(false);
            btn_depl_bg.setEnabled(false);
            btn_depl_hd.setEnabled(false);
            btn_depl_droite.setEnabled(false);
            btn_depl_bd.setEnabled(false);
            btn_depl_haut.setEnabled(false);
            btn_depl_bas.setEnabled(false);
        }
    }

    private void btn_pers_fonceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //recuperation des coordonees du perso choisi
        for (int i = 0; i <= 4; i++) {
            for (int j = 0; j <= 4; j++) {
                if (plateau.plateau[i][j].perso_courant == joueurCourant.liste_perso[1]) {
                    X = i;
                    Y = j;
                }
            }
        }
        //activation des bouton de deplacements
        btn_depl_hg.setEnabled(true);
        btn_depl_gauche.setEnabled(true);
        btn_depl_bg.setEnabled(true);
        btn_depl_hd.setEnabled(true);
        btn_depl_droite.setEnabled(true);
        btn_depl_bd.setEnabled(true);
        btn_depl_haut.setEnabled(true);
        btn_depl_bas.setEnabled(true);
    }

    private void btn_pers_clairActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //recuperation des coordonees du perso choisi
        for (int i = 0; i <= 4; i++) {
            for (int j = 0; j <= 4; j++) {
                if (plateau.plateau[i][j].perso_courant == joueurCourant.liste_perso[0]) {
                    X = i;
                    Y = j;
                }
            }
        }
        //activation des bouton de deplacements
        btn_depl_hg.setEnabled(true);
        btn_depl_gauche.setEnabled(true);
        btn_depl_bg.setEnabled(true);
        btn_depl_hd.setEnabled(true);
        btn_depl_droite.setEnabled(true);
        btn_depl_bd.setEnabled(true);
        btn_depl_haut.setEnabled(true);
        btn_depl_bas.setEnabled(true);
    }

    private void btn_depl_hautActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (plateau.deplacement_possible(X, Y, X + 1, Y)) {
            plateau.plateau[X + 1][Y].perso_courant = plateau.plateau[X][Y].perso_courant;
            plateau.plateau[X][Y].perso_courant = null;
            btn_depl_hg.setEnabled(false);
            btn_depl_gauche.setEnabled(false);
            btn_depl_bg.setEnabled(false);
            btn_depl_hd.setEnabled(false);
            btn_depl_droite.setEnabled(false);
            btn_depl_bd.setEnabled(false);
            btn_depl_haut.setEnabled(false);
            btn_depl_bas.setEnabled(false);
        }
    }

    private void btn_depl_gaucheActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (plateau.deplacement_possible(X, Y, X, Y - 1)) {
            plateau.plateau[X][Y - 1].perso_courant = plateau.plateau[X][Y].perso_courant;
            plateau.plateau[X][Y].perso_courant = null;
            btn_depl_hg.setEnabled(false);
            btn_depl_gauche.setEnabled(false);
            btn_depl_bg.setEnabled(false);
            btn_depl_hd.setEnabled(false);
            btn_depl_droite.setEnabled(false);
            btn_depl_bd.setEnabled(false);
            btn_depl_haut.setEnabled(false);
            btn_depl_bas.setEnabled(false);
        }
    }

    private void btn_depl_bgActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (plateau.deplacement_possible(X, Y, X - 1, Y - 1)) {
            plateau.plateau[X - 1][Y - 1].perso_courant = plateau.plateau[X][Y].perso_courant;
            plateau.plateau[X][Y].perso_courant = null;
            btn_depl_hg.setEnabled(false);
            btn_depl_gauche.setEnabled(false);
            btn_depl_bg.setEnabled(false);
            btn_depl_hd.setEnabled(false);
            btn_depl_droite.setEnabled(false);
            btn_depl_bd.setEnabled(false);
            btn_depl_haut.setEnabled(false);
            btn_depl_bas.setEnabled(false);
        }
    }

    private void btn_depl_droiteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (plateau.deplacement_possible(X, Y, X, Y + 1)) {
            plateau.plateau[X][Y + 1].perso_courant = plateau.plateau[X][Y].perso_courant;
            plateau.plateau[X][Y].perso_courant = null;
            btn_depl_hg.setEnabled(false);
            btn_depl_gauche.setEnabled(false);
            btn_depl_bg.setEnabled(false);
            btn_depl_hd.setEnabled(false);
            btn_depl_droite.setEnabled(false);
            btn_depl_bd.setEnabled(false);
            btn_depl_haut.setEnabled(false);
            btn_depl_bas.setEnabled(false);
        }
    }

    private void btn_depl_bdActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (plateau.deplacement_possible(X, Y, X - 1, Y + 1)) {
            plateau.plateau[X - 1][Y + 1].perso_courant = plateau.plateau[X][Y].perso_courant;
            plateau.plateau[X][Y].perso_courant = null;
            btn_depl_hg.setEnabled(false);
            btn_depl_gauche.setEnabled(false);
            btn_depl_bg.setEnabled(false);
            btn_depl_hd.setEnabled(false);
            btn_depl_droite.setEnabled(false);
            btn_depl_bd.setEnabled(false);
            btn_depl_haut.setEnabled(false);
            btn_depl_bas.setEnabled(false);
        }
    }

    private void btn_depl_basActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (plateau.deplacement_possible(X, Y, X - 1, Y)) {
            plateau.plateau[X - 1][Y].perso_courant = plateau.plateau[X][Y].perso_courant;
            plateau.plateau[X][Y].perso_courant = null;
            btn_depl_hg.setEnabled(false);
            btn_depl_gauche.setEnabled(false);
            btn_depl_bg.setEnabled(false);
            btn_depl_hd.setEnabled(false);
            btn_depl_droite.setEnabled(false);
            btn_depl_bd.setEnabled(false);
            btn_depl_haut.setEnabled(false);
            btn_depl_bas.setEnabled(false);
        }
    }

    private void btn_demarrerpartieActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        pnl_commande.setVisible(true);
        pnl_infos.setVisible(true);
        initialiserPartie();
        plateau_jeu.repaint();
        btn_demarrerpartie.setEnabled(false);
    }

    public void initialiserPartie() {
        listeJoueurs[0] = new Joueur(nom_joueur1.getText());
        listeJoueurs[1] = new Joueur(nom_joueur2.getText());
        joueurCourant = listeJoueurs[0];
    }

    public void joueurSuivant() {
        if (joueurCourant == listeJoueurs[1]) {
            joueurCourant = listeJoueurs[0];
        } else {
            joueurCourant = listeJoueurs[1];
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_demarrerpartie;
    private javax.swing.JButton btn_demarrerpartie1;
    private javax.swing.JButton btn_pers_clair;
    private javax.swing.JButton btn_pers_fonce;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbl_couleur_j1;
    private javax.swing.JLabel lbl_couleur_j2;
    private javax.swing.JLabel lbl_joueur1;
    private javax.swing.JLabel lbl_joueur2;
    private javax.swing.JLabel lbl_joueurcourant;
    private javax.swing.JLabel lbl_nom_joueurcourant;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JPanel plateau_jeu;
    private javax.swing.JPanel pnl_commande;
    private javax.swing.JPanel pnl_info_joueur;
    private javax.swing.JPanel pnl_infos;
    private javax.swing.JPanel pnl_joueur_courant;
    // End of variables declaration//GEN-END:variables
}
